security:
    encoders:
            App\Entity\AppUser:
                algorithm: bcrypt
    providers:
            app_db:
                    entity:
                        class: App\Entity\AppUser
                        property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        administration_login:
                pattern: ^/administration
                anonymous: ~
                form_login:
                          login_path: login_admin
                          check_path: login_admin
                provider: app_db
                logout:
                      path:   ^/administration
                      target: /
        audit_login:
                        pattern: ^/voir-audit/audit
                        anonymous: ~
                        form_login:
                                  login_path: login_audit
                                  check_path: login_audit
                        provider: app_db
                        logout:
                              path:   ^/administration
                              target: /
        main_login:
            pattern: ^/
            anonymous: ~
            user_checker: App\Security\UserChecker
            form_login:
                       login_path: login
                       check_path: login
                       csrf_token_generator: security.csrf.token_manager
            provider: app_db
            logout:
                    path:   logout
                    target: /
    role_hierarchy:
            ROLE_CREATOR: ROLE_USER
            ROLE_ADMIN_USER: ROLE_CREATOR
            ROLE_ADMIN_CONTENT: ROLE_CREATOR
            ROLE_ADMIN_CUSTOMER: ROLE_CREATOR
            ROLE_ADMIN_GLOBAL: [ROLE_ADMIN_USER, ROLE_ADMIN_CONTENT, ROLE_ADMIN_CUSTOMER]
            ROLE_SUPER_ADMIN: ROLE_ADMIN_GLOBAL
    access_control:
      - { path: ^/administration/utilisateurs, roles: ROLE_ADMIN_USER }
      - { path: ^/administration/contenu-audits, roles: ROLE_ADMIN_CONTENT }
      - { path: ^/administration/clients, roles: ROLE_ADMIN_CUSTOMER }
      - { path: ^/audit/créer, roles: ROLE_CREATOR }
      - { path: ^/$, roles: ROLE_USER }
      - { path: ^/profile, roles: ROLE_USER}
      - { path: ~/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }



